# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  certificates:
    build:
      context: certificates
    volumes:
      - .:/host
  mailpit:
    # see https://hub.docker.com/r/axllent/mailpit
    # see https://github.com/axllent/mailpit
    # see https://mailpit.axllent.org/docs/install/docker/
    image: axllent/mailpit:v1.20.7
    command:
      - --smtp-auth-accept-any
      - --smtp-auth-allow-insecure
    ports:
      # smtp.
      # http://localhost:1025
      #- 1025:1025
      # http.
      # http://localhost:8025
      - 8025:8025
    environment:
      - MP_SMTP_TLS_KEY=/etc/ssl/private/mail.test-key.pem
      - MP_SMTP_TLS_CERT=/etc/ssl/private/mail.test-crt.pem
      - MP_UI_TLS_KEY=/etc/ssl/private/mail.test-key.pem
      - MP_UI_TLS_CERT=/etc/ssl/private/mail.test-crt.pem
    volumes:
      - ./tmp/keycloak-ca/mail.test-key.pem:/etc/ssl/private/mail.test-key.pem:ro
      - ./tmp/keycloak-ca/mail.test-crt.pem:/etc/ssl/private/mail.test-crt.pem:ro
    networks:
      default:
        aliases:
          - mail.test
    restart: on-failure
  keycloak:
    build:
      context: keycloak
    ports:
      - 8443:8443
    environment:
      - KC_HOSTNAME=keycloak.test
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      - start-dev
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/etc/pki/ca-trust/source/anchors/keycloak.crt:ro
      - ./tmp/keycloak-ca/keycloak.test-key.p12:/etc/pki/keycloak.test-key.p12:ro
    restart: on-failure
    depends_on:
      - mailpit
    networks:
      default:
        aliases:
          - keycloak.test
  init:
    depends_on:
      - keycloak
    build:
      dockerfile: Dockerfile.init
    environment:
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/host/terraform.log
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - .:/host
  destroy:
    profiles:
      - destroy
    build:
      dockerfile: Dockerfile.init
    environment:
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/host/terraform.log
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - .:/host
    entrypoint: terraform
    command:
      - destroy
      - -auto-approve
  example-csharp-public-device:
    profiles:
      - example-csharp-public-device
    build:
      context: clients/example-csharp-public-device
  example-csharp-public-device-test:
    profiles:
      - example-csharp-public-device
    build:
      context: clients/example-csharp-public-device-test
    environment:
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./clients/example-csharp-public-device-test/playwright-report/:/app/playwright-report/
      - ./clients/example-csharp-public-device-test/test-results/:/app/test-results/
  example-csharp-client-credentials-server:
    build:
      context: clients/example-csharp-client-credentials-server
    ports:
      - 8027:8027
    environment:
      - EXAMPLE_URL=https://example-csharp-client-credentials-server.test:8027
      - EXAMPLE_OIDC_ISSUER_URL=https://keycloak.test:8443/realms/example
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./tmp/keycloak-ca/example-csharp-client-credentials-server.test-key.p12:/etc/ssl/private/example-csharp-client-credentials-server.test-key.p12:ro
    networks:
      default:
        aliases:
          - example-csharp-client-credentials-server.test
  example-csharp-client-credentials-server-test:
    profiles:
      - test
    build:
      context: clients/example-csharp-client-credentials-server-test
    environment:
      - EXAMPLE_SERVER_URL=https://example-csharp-client-credentials-server.test:8027
      - EXAMPLE_OIDC_ISSUER_URL=https://keycloak.test:8443/realms/example
      - EXAMPLE_OAUTH_CLIENT_ID=example-csharp-client-credentials-server-test
      - EXAMPLE_OAUTH_CLIENT_SECRET=example
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
  example-go-client-credentials-server:
    build:
      context: clients/example-go-client-credentials-server
    ports:
      - 8026:8026
    environment:
      - EXAMPLE_URL=https://example-go-client-credentials-server.test:8026
      - EXAMPLE_OAUTH_CLIENT_ID=example-go-client-credentials-server
      - EXAMPLE_OAUTH_CLIENT_SECRET=example
      - EXAMPLE_OAUTH_TOKEN_INTROSPECTION_URL=https://keycloak.test:8443/realms/example/protocol/openid-connect/token/introspect
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./tmp/keycloak-ca/example-go-client-credentials-server.test-key.pem:/etc/ssl/private/example-go-client-credentials-server.test-key.pem:ro
      - ./tmp/keycloak-ca/example-go-client-credentials-server.test-crt.pem:/etc/ssl/private/example-go-client-credentials-server.test-crt.pem:ro
    networks:
      default:
        aliases:
          - example-go-client-credentials-server.test
  example-go-client-credentials-server-test:
    profiles:
      - example-go-client-credentials-server-test
    build:
      context: clients/example-go-client-credentials-server-test
    environment:
      - EXAMPLE_SERVER_URL=https://example-go-client-credentials-server.test:8026
      - EXAMPLE_OAUTH_CLIENT_ID=example-go-client-credentials-server-test
      - EXAMPLE_OAUTH_CLIENT_SECRET=example
      - EXAMPLE_OAUTH_TOKEN_URL=https://keycloak.test:8443/realms/example/protocol/openid-connect/token
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
  example-go-confidential:
    build:
      context: clients/example-go-confidential
    ports:
      - 8081:8081
    environment:
      - EXAMPLE_URL=https://example-go-confidential.test:8081
      - EXAMPLE_OIDC_ISSUER_URL=https://keycloak.test:8443/realms/example
      - EXAMPLE_OIDC_CLIENT_ID=example-go-confidential
      - EXAMPLE_OIDC_CLIENT_SECRET=example
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./tmp/keycloak-ca/example-go-confidential.test-key.pem:/etc/ssl/private/example-go-confidential.test-key.pem:ro
      - ./tmp/keycloak-ca/example-go-confidential.test-crt.pem:/etc/ssl/private/example-go-confidential.test-crt.pem:ro
    networks:
      default:
        aliases:
          - example-go-confidential.test
  example-go-confidential-test:
    profiles:
      - test
    build:
      context: clients/example-go-confidential-test
    environment:
      - EXAMPLE_LOGIN_URL=https://example-go-confidential.test:8081/auth/login
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./clients/example-go-confidential-test/playwright-report/:/app/playwright-report/
      - ./clients/example-go-confidential-test/test-results/:/app/test-results/
  example-go-saml:
    build:
      context: clients/example-go-saml
    ports:
      - 8082:8082
    command:
      - -listen=https://example-go-saml.test:8082
      - -entity-id=example-go-saml
      - -idp-metadata=https://keycloak.test:8443/realms/example/protocol/saml/descriptor
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./tmp/keycloak-ca/example-go-saml.test-key.pem:/etc/ssl/private/example-go-saml.test-key.pem:ro
      - ./tmp/keycloak-ca/example-go-saml.test-crt.pem:/etc/ssl/private/example-go-saml.test-crt.pem:ro
      - ./clients/example-go-saml/example-go-saml-key.pem:/example-go-saml-key.pem:ro
      - ./clients/example-go-saml/example-go-saml-crt.pem:/example-go-saml-crt.pem:ro
    networks:
      default:
        aliases:
          - example-go-saml.test
  example-go-saml-test:
    profiles:
      - test
    build:
      context: clients/example-go-saml-test
    environment:
      - EXAMPLE_LOGIN_URL=https://example-go-saml.test:8082/login
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./clients/example-go-saml-test/playwright-report/:/app/playwright-report/
      - ./clients/example-go-saml-test/test-results/:/app/test-results/
  example-react-public:
    build:
      context: clients/example-react-public
    ports:
      - 8083:8083
    environment:
      - EXAMPLE_OIDC_AUTHORITY=https://keycloak.test:8443/realms/example
      - EXAMPLE_OIDC_CLIENT_ID=example-react-public
      - EXAMPLE_OIDC_REDIRECT_URI=https://example-react-public.test:8083/
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./tmp/keycloak-ca/example-react-public.test-key.pem:/etc/ssl/private/example-react-public.test-key.pem:ro
      - ./tmp/keycloak-ca/example-react-public.test-crt.pem:/etc/ssl/private/example-react-public.test-crt.pem:ro
    networks:
      default:
        aliases:
          - example-react-public.test
  example-react-public-test:
    profiles:
      - test
    build:
      context: clients/example-react-public-test
    environment:
      - EXAMPLE_LOGIN_URL=https://example-react-public.test:8083
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./tmp/keycloak-ca/keycloak-ca-crt.pem:/usr/local/share/ca-certificates/keycloak.crt:ro
      - ./clients/example-react-public-test/playwright-report/:/app/playwright-report/
      - ./clients/example-react-public-test/test-results/:/app/test-results/
