# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025
  keycloak:
    # see https://quay.io/repository/keycloak/keycloak
    # see https://www.keycloak.org/docs/latest/release_notes/index.html
    # see https://www.keycloak.org/server/containers
    # see https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile
    # see https://github.com/keycloak/keycloak/releases
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    restart: on-failure
    depends_on:
      - mailhog
    networks:
      default:
        aliases:
          - keycloak.test
  init:
    depends_on:
      - keycloak
    build:
      dockerfile: Dockerfile.init
    environment:
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/host/terraform.log
    volumes:
      - .:/host
  destroy:
    profiles:
      - destroy
    build:
      dockerfile: Dockerfile.init
    environment:
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/host/terraform.log
    volumes:
      - .:/host
    entrypoint: terraform
    command:
      - destroy
      - -auto-approve
  example-csharp-public-device:
    profiles:
      - example-csharp-public-device
    build:
      context: clients/example-csharp-public-device
  example-csharp-public-device-test:
    profiles:
      - example-csharp-public-device
    build:
      context: clients/example-csharp-public-device-test
    environment:
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./clients/example-csharp-public-device-test/playwright-report/:/app/playwright-report/
      - ./clients/example-csharp-public-device-test/test-results/:/app/test-results/
  example-go-confidential:
    build:
      context: clients/example-go-confidential
    ports:
      - 8081:8081
    environment:
      - EXAMPLE_URL=http://example-go-confidential.test:8081
      - EXAMPLE_OIDC_ISSUER_URL=http://keycloak.test:8080/realms/example
      - EXAMPLE_OIDC_CLIENT_ID=example-go-confidential
      - EXAMPLE_OIDC_CLIENT_SECRET=example
    networks:
      default:
        aliases:
          - example-go-confidential.test
  example-go-confidential-test:
    profiles:
      - test
    build:
      context: clients/example-go-confidential-test
    environment:
      - EXAMPLE_LOGIN_URL=http://example-go-confidential.test:8081/auth/login
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./clients/example-go-confidential-test/playwright-report/:/app/playwright-report/
      - ./clients/example-go-confidential-test/test-results/:/app/test-results/
  example-go-saml:
    build:
      context: clients/example-go-saml
    ports:
      - 8082:8082
    command:
      - -listen=http://example-go-saml.test:8082
      - -entity-id=example-go-saml
      - -idp-metadata=http://keycloak.test:8080/realms/example/protocol/saml/descriptor
    volumes:
      - ./clients/example-go-saml/example-go-saml-key.pem:/example-go-saml-key.pem:ro
      - ./clients/example-go-saml/example-go-saml-crt.pem:/example-go-saml-crt.pem:ro
    networks:
      default:
        aliases:
          - example-go-saml.test
  example-go-saml-test:
    profiles:
      - test
    build:
      context: clients/example-go-saml-test
    environment:
      - EXAMPLE_LOGIN_URL=http://example-go-saml.test:8082/login
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./clients/example-go-saml-test/playwright-report/:/app/playwright-report/
      - ./clients/example-go-saml-test/test-results/:/app/test-results/
  example-react-public:
    build:
      context: clients/example-react-public
    ports:
      - 8083:8083
    environment:
      - EXAMPLE_OIDC_AUTHORITY=http://keycloak.test:8080/realms/example
      - EXAMPLE_OIDC_CLIENT_ID=example-react-public
      - EXAMPLE_OIDC_REDIRECT_URI=http://example-react-public.test:8083/
    networks:
      default:
        aliases:
          - example-react-public.test
  example-react-public-test:
    profiles:
      - test
    build:
      context: clients/example-react-public-test
    environment:
      - EXAMPLE_LOGIN_URL=http://example-react-public.test:8083
      - EXAMPLE_USERNAME=alice
      - EXAMPLE_PASSWORD=alice
    volumes:
      - ./clients/example-react-public-test/playwright-report/:/app/playwright-report/
      - ./clients/example-react-public-test/test-results/:/app/test-results/
