# syntax=docker.io/docker/dockerfile:1.9

FROM hashicorp/terraform:1.9.5

RUN <<EOF
apk add --update --no-cache \
  ca-certificates \
  postgresql-client \
  python3 \
  py3-psycopg2
EOF

VOLUME /host

WORKDIR /host

ENTRYPOINT ["ash", "init.sh"]
