# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025
  keycloak:
    # see https://quay.io/repository/keycloak/keycloak
    # see https://www.keycloak.org/server/containers
    # see https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    restart: on-failure
    depends_on:
      - mailhog
    networks:
      default:
        aliases:
          - keycloak.test
  init:
    depends_on:
      - keycloak
    build:
      dockerfile: Dockerfile.init
    environment:
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/host/terraform.log
    volumes:
      - .:/host
  destroy:
    profiles:
      - destroy
    build:
      dockerfile: Dockerfile.init
    environment:
      - TF_LOG=DEBUG
      - TF_LOG_PATH=/host/terraform.log
    volumes:
      - .:/host
    entrypoint: terraform
    command:
      - destroy
      - -auto-approve
