# syntax=docker.io/docker/dockerfile:1.7

FROM hashicorp/terraform:1.7.4

RUN <<EOF
apk add --update --no-cache \
  postgresql-client \
  python3 \
  py3-psycopg2
EOF

VOLUME /host

WORKDIR /host

ENTRYPOINT ["ash", "init.sh"]
